version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # JUnit Pioneer 2.x requires Java 11, so ignore it (the 1.x branch is not being updated anymore)
      - dependency-name: "org.junit-pioneer:junit-pioneer"
    groups:
      dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "dsingley"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    assignees:
      - "dsingley"
